name: Android CI

on:
  push:
    tags-ignore:
      - 'v*'
    branches:
      - '*'
  pull_request:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup APK Signing Key
        if: github.event_name == 'push'
        run: |
            echo ${{ secrets.KEYSTORE }} | base64 --decode > keystore.jks
            echo ${{ secrets.GRADLE_PROPERTIES}} | base64 --decode >> gradle.properties

      - name: Build with Gradle
        run: ./gradlew assembleDebug assembleRelease

      - name: Upload Artifact (Release)
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/release/*.apk

      - name: Upload Artifact (Debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk